// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnwj4bObDX-7VGKPhm_TWVdbZ9jpljBJo',
    appId: '1:1074990192023:web:2635decbed6c727484a0d2',
    messagingSenderId: '1074990192023',
    projectId: 'nimadhi-46e15',
    authDomain: 'nimadhi-46e15.firebaseapp.com',
    databaseURL: 'https://nimadhi-46e15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimadhi-46e15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBt_1bMTIokZcTqPAnXvlR-mSEpKz0Lg',
    appId: '1:1074990192023:android:f028a71be75ac35884a0d2',
    messagingSenderId: '1074990192023',
    projectId: 'nimadhi-46e15',
    databaseURL: 'https://nimadhi-46e15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimadhi-46e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBSfqd5hKjAD4aC-6Fqmu1hkFuDbrNPd4',
    appId: '1:1074990192023:ios:64c945bf12483de984a0d2',
    messagingSenderId: '1074990192023',
    projectId: 'nimadhi-46e15',
    databaseURL: 'https://nimadhi-46e15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimadhi-46e15.appspot.com',
    androidClientId: '1074990192023-3t0hopfob5faq8rncq0j6ingt54fsndm.apps.googleusercontent.com',
    iosClientId: '1074990192023-638aqp69aon09bprvbdc5vn0copl7lcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimmadhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBSfqd5hKjAD4aC-6Fqmu1hkFuDbrNPd4',
    appId: '1:1074990192023:ios:826eefec903966fc84a0d2',
    messagingSenderId: '1074990192023',
    projectId: 'nimadhi-46e15',
    databaseURL: 'https://nimadhi-46e15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimadhi-46e15.appspot.com',
    androidClientId: '1074990192023-3t0hopfob5faq8rncq0j6ingt54fsndm.apps.googleusercontent.com',
    iosClientId: '1074990192023-oun9m3r32aapc1aqme0fbkef895lilmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimmadhi.RunnerTests',
  );
}
